name: xpinmame_lisy
on:
  push:

jobs:
  build:
    name: ${{ matrix.cpu_info }}/${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [zero_raspios, zero2_64_raspios, zero_raspian]
        include:
          - target: zero_raspios
            cpu: arm1176
            cpu_info: raspberrypi_zero_w
            os: raspios
            base_image: raspios_lite:latest
          - target: zero2_64_raspios
            cpu: cortex-a53
            cpu_info: raspberrypi_zero2_w_arm64
            os: raspios
            base_image: raspios_lite_arm64:latest
          - target: zero_raspian
            cpu: arm1176
            cpu_info: raspberrypi_zero_w
            os: raspbian
            base_image: raspbian_lite:2020-02-13
    steps:
      - name: Checkout pinmame
        uses: actions/checkout@v2

      - name: Checkout WiringPi
        uses: actions/checkout@v2
        with:
            repository: WiringPi/WiringPi
            ref: master
            path: WiringPi

      - name: Make in chroot environment
        uses: pguyot/arm-runner-action@v2
        id: arm_runner_make
        with:
          base_image: ${{ matrix.base_image }}
          optimize_image: yes
          image_additional_mb: 1024
          cpu: ${{ matrix.cpu }}
          cpu_info: cpuinfo/${{ matrix.cpu_info }}
          copy_repository_path: /opt/pinmame
          copy_artifact_path: xpinmame.vid_lisy
          commands: |
            apt-get update -y --allow-releaseinfo-change
            apt-get install --no-install-recommends -y libasound2-dev libsdl2.dev libsdl2-mixer-dev libi2c-dev
            cd /opt/pinmame/WiringPi
            ./build
            cd /opt/pinmame
            make -f makefile.lisy

      - name: Upload xmpinmame binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: LISY ${{ matrix.cpu_info }} ${{ matrix.os }}
          path: xpinmame.vid_lisy
